@startuml
class Chat {
    + Id : Guid <<get>> <<set>>
    + Name : string? <<get>> <<set>>
    + Lastmessage : string? <<get>> <<set>>
    + ChatAdministrator : Guid? <<get>> <<set>>
    + Messages : ICollection<ChatMessage> <<get>> <<set>>
    + ChatUsers : ICollection<ChatUser> <<get>> <<set>>
}
@enduml
