@startuml
!include .\\.\MySuperApi\Program.puml
!include .\\.\MySuperApi\Areas\AppMappingProfile.puml
!include .\\.\MySuperApi\Controllers\AccountController.puml
!include .\\.\MySuperApi\Controllers\AuthController.puml
!include .\\.\MySuperApi\Controllers\MessageController.puml
!include .\\.\MySuperApi\DTOs\CreateChatDto.puml
!include .\\.\MySuperApi\DTOs\UserDto.puml
!include .\\.\MySuperApi\DTOs\UserFullDto.puml
!include .\\.\MySuperApi\DTOs\UserIdDto.puml
!include .\\.\MySuperApi\Extensions\ServiceCollectionExtensions.puml
!include .\\.\MySuperApi\HubConfig\UserHub.puml
!include .\\.\MySuperApi\JWTModule\RefreshToken.puml
!include .\\.\MySuperApi\JWTModule\RegisterUserDto.puml
!include .\\.\MySuperApi\Migrations\20230522180449_initDb.puml
!include .\\.\MySuperApi\Migrations\20230522180449_initDb.Designer.puml
!include .\\.\MySuperApi\Migrations\20230522181044_profileImage.puml
!include .\\.\MySuperApi\Migrations\20230522181044_profileImage.Designer.puml
!include .\\.\MySuperApi\Migrations\20230522181332_profileImage2.puml
!include .\\.\MySuperApi\Migrations\20230522181332_profileImage2.Designer.puml
!include .\\.\MySuperApi\Migrations\20230522183921_profileImage3.puml
!include .\\.\MySuperApi\Migrations\20230522183921_profileImage3.Designer.puml
!include .\\.\MySuperApi\Migrations\20230524133246_imgStorage.puml
!include .\\.\MySuperApi\Migrations\20230524133246_imgStorage.Designer.puml
!include .\\.\MySuperApi\Migrations\20230524135329_removeCurrentImageFromUser.puml
!include .\\.\MySuperApi\Migrations\20230524135329_removeCurrentImageFromUser.Designer.puml
!include .\\.\MySuperApi\Migrations\20230524200954_chat.puml
!include .\\.\MySuperApi\Migrations\20230524200954_chat.Designer.puml
!include .\\.\MySuperApi\Migrations\20230526152549_chatLastMessage.puml
!include .\\.\MySuperApi\Migrations\20230526152549_chatLastMessage.Designer.puml
!include .\\.\MySuperApi\Migrations\20230531131646_imageBytes.puml
!include .\\.\MySuperApi\Migrations\20230531131646_imageBytes.Designer.puml
!include .\\.\MySuperApi\Migrations\20230531185113_superUpdate.puml
!include .\\.\MySuperApi\Migrations\20230531185113_superUpdate.Designer.puml
!include .\\.\MySuperApi\Migrations\20230608151554_chatOwner.puml
!include .\\.\MySuperApi\Migrations\20230608151554_chatOwner.Designer.puml
!include .\\.\MySuperApi\Migrations\AppDbContextModelSnapshot.puml
!include .\\.\MySuperApi\Models\AppDbContext.puml
!include .\\.\MySuperApi\Models\AppUser.puml
!include .\\.\MySuperApi\Models\ProfileImageClaims.puml
!include .\\.\MySuperApi\Models\UserProfileImage.puml
!include .\\.\MySuperApi\Models\UserProfileImageStorage.puml
!include .\\.\MySuperApi\Models\MessageModels\Chat.puml
!include .\\.\MySuperApi\Models\MessageModels\ChatMessage.puml
!include .\\.\MySuperApi\Models\MessageModels\ChatUser.puml
!include .\\.\MySuperApi\Repositories\Implementation\ChatRepository.puml
!include .\\.\MySuperApi\Repositories\Interfaces\IChatRepository.puml
!include .\\.\MySuperApi\Services\PathLogic\IPathMaster.puml
!include .\\.\MySuperApi\Services\PathLogic\PathMaster.puml
!include .\\.\MySuperApi\Services\ProfileImageService\IProfileImageService.puml
!include .\\.\MySuperApi\Services\ProfileImageService\ProfileImageService.puml
!include .\\.\MySuperApi\Services\UserService\IUserService.puml
!include .\\.\MySuperApi\Services\UserService\UserService.puml
!include .\\.\MySuperApi\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\.\MySuperApi\obj\Debug\net7.0\MySuperApi.AssemblyInfo.puml
!include .\\.\MySuperApi\obj\Debug\net7.0\MySuperApi.GlobalUsings.g.puml
!include .\\.\MySuperApi\obj\Debug\net7.0\MySuperApi.MvcApplicationPartsAssemblyInfo.puml
!include .\\.\MySuperApi\obj\Release\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\.\MySuperApi\obj\Release\net7.0\MySuperApi.AssemblyInfo.puml
!include .\\.\MySuperApi\obj\Release\net7.0\MySuperApi.GlobalUsings.g.puml
!include .\\.\MySuperApi\obj\Release\net7.0\MySuperApi.MvcApplicationPartsAssemblyInfo.puml
@enduml
