@startuml
class AppDbContext {
    + Users : DbSet<AppUser> <<get>> <<set>>
    + ProfileImageClaims : DbSet<ProfileImageClaims> <<get>> <<set>>
    + ProfileImages : DbSet<UserProfileImage> <<get>> <<set>>
    + ProfileImageStorages : DbSet<UserProfileImageStorage> <<get>> <<set>>
    + Messages : DbSet<ChatMessage> <<get>> <<set>>
    + Chats : DbSet<Chat> <<get>> <<set>>
    + ChatUsers : DbSet<ChatUser> <<get>> <<set>>
    + AppDbContext(options:DbContextOptions<AppDbContext>)
}
DbContext <|-- AppDbContext
@enduml
