@startuml
class AppUser {
    + Id : Guid <<get>> <<set>>
    + Username : string <<get>> <<set>>
    + Surname : string <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + PasswordHash : byte[]? <<get>> <<set>>
    + PasswordSalt : byte[]? <<get>> <<set>>
    + RefreshToken : string <<get>> <<set>>
    + TokenCreated : DateTime <<get>> <<set>>
    + TokenExpires : DateTime <<get>> <<set>>
    + AccountCreated : DateTime <<get>> <<set>>
    + AccountLastTimeEdited : DateTime <<get>> <<set>>
    + LastTimeOnline : DateTime <<get>> <<set>>
    + CurrentImageBytes : byte[]? <<get>> <<set>>
    + UserProfileImages : ICollection<UserProfileImage> <<get>> <<set>>
    + SentMessages : ICollection<ChatMessage> <<get>> <<set>>
    + ReceivedMessages : ICollection<ChatMessage> <<get>> <<set>>
}
@enduml
