@startuml
class UserProfileImage {
    + ImageId : Guid <<get>> <<set>>
    + AppUser : AppUser? <<get>> <<set>>
    + AppUserId : Guid <<get>> <<set>>
    + FileName : string? <<get>> <<set>>
    + ImagePath : string? <<get>> <<set>>
    + FormImage : IFormFile? <<get>> <<set>>
}
@enduml
