@startuml
class UserProfileImageStorage {
    + Id : Guid <<get>> <<set>>
    + UserId : Guid <<get>> <<set>>
    + User : AppUser? <<get>> <<set>>
    + ProfileImageId : Guid <<get>> <<set>>
    + ProfileImage : UserProfileImage? <<get>> <<set>>
}
@enduml
